rule all:
    input:
        "data/interim/interactions_clean.csv",
        "data/interim/items_clean.csv",
        "data/interim/users_clean.csv",
        "data/models/items_processed_for_train.csv",
        "data/models/items_processed_for_submit.csv"
        "data/models/users_processed.csv",
        "data/models/implicit_scores_for_train.csv",
        "data/models/implicit_scores_for_submit.csv",
        "data/models/catboost_trained_model.pkl",

rule get_data:
    output:
        "data/raw/interactions.csv",
        "data/raw/items.csv",
        "data/raw/sample_submission.csv",
        "data/raw/users.csv"
    shell:
        "source src/get_data.sh"

rule preprocess:
    input:
        "data/raw/interactions.csv",
        "data/raw/items.csv",
        "data/raw/users.csv"
    output:
        "data/interim/interactions_clean.csv",
        "data/interim/items_clean.csv",
        "data/interim/users_clean.csv"
    shell:
        "python src/data/preprocess.py"

rule add_item_stats:
    input:
        "data/interim/interactions_clean.csv",
        "data/interim/items_clean.csv",
        "data/interim/users_clean.csv"
    output:
        "data/models/items_processed_for_train.csv",
        "data/models/items_processed_for_submit.csv"
    shell:
        "python src/features/add_item_stats.py {input[0]} {input[1]} {input[2]} {output[0]} {output[1]}"                     

rule add_user_stats:
    input:
        "data/interim/interactions_clean.csv",
        "data/interim/users_clean.csv"
    output:
        "data/models/users_processed.csv",
    shell:
        "python src/features/add_user_stats.py {input[0]} {input[1]} {output[0]}"

rule train_first_stage:
    input:
        "data/interim/interactions_clean.csv",
        "data/raw/sample_submission.csv",
    output:
        "data/models/implicit_scores_for_train.csv",
        "data/models/implicit_scores_for_submit.csv",
    shell:
        "python src/models/train_first_stage.py {input[0]} {input[1]} {output[0]} {output[1]}" 

rule train_second_stage:
    input:
        "data/interim/interactions_clean.csv",
        "data/models/users_processed.csv",
        "data/models/items_processed_for_train.csv",
        "data/models/implicit_scores_for_train.csv",        
    output:
        "data/models/catboost_trained_model.pkl",
    shell:
        "python src/models/train_second_stage.py {input[0]} {input[1]} {input[2]} {input[3] {output[0]}"


