rule all:
    input:
        "models/submission.csv"

rule get_data:
    output:
        "data/raw/interactions.csv",
        "data/raw/items.csv",
        "data/raw/sample_submission.csv",
        "data/raw/users.csv"
    shell:
        "source src/get_data.sh"

rule preprocess:
    input:
        "data/raw/interactions.csv",
        "data/raw/items.csv",
        "data/raw/users.csv"
    output:
        "data/interim/interactions_clean.csv",
        "data/interim/items_clean.csv",
        "data/interim/users_clean.csv"
    shell:
        "python src/data/preprocess.py {input} {output}"

rule add_item_stats:
    input:
        "data/interim/interactions_clean.csv",
        "data/interim/items_clean.csv",
        "data/interim/users_clean.csv"
    output:
        "data/processed/items_processed_for_train.csv",
        "data/processed/items_processed_for_submit.csv"
    shell:
        "python src/features/add_item_stats.py {input} {output}"                     

rule add_user_stats:
    input:
        "data/interim/interactions_clean.csv",
        "data/interim/users_clean.csv"
    output:
        "data/processed/users_processed.csv",
    shell:
        "python src/features/add_user_stats.py {input} {output}"

rule train_first_stage:
    input:
        "data/interim/interactions_clean.csv",
        "data/raw/sample_submission.csv",
    output:
        "data/processed/implicit_scores_for_train.csv",
        "data/processed/implicit_scores_for_submit.csv",
    shell:
        "python src/models/train_first_stage.py {input} {output}" 

rule train_second_stage:
    input:
        "data/interim/interactions_clean.csv",
        "data/processed/users_processed.csv",
        "data/processed/items_processed_for_train.csv",
        "data/processed/implicit_scores_for_train.csv",   
    output:
        "models/catboost_trained_model.pkl",
        "data/train/x_train.csv",
        "data/train/y_train.csv",
        "data/train/x_val.csv",
        "data/train/y_val.csv",
    shell:
        "python src/models/train_second_stage.py {input} {output}"


rule prepare_submission:
    input:
        "data/interim/interactions_clean.csv",
        "data/processed/users_processed.csv",
        "data/processed/items_processed_for_submit.csv",
        "data/processed/implicit_scores_for_submit.csv", 
        "data/raw/sample_submission.csv",
        "models/catboost_trained_model.pkl",
    output:
        "models/submission.csv"
    shell:
        "python src/models/prepare_submission.py {input} {output}"
